

image: python:3.9

stages:
  - deploy
  - pages

deploy_job:
  stage: deploy
  script:
    - pip install mkdocs
    - pip install mkdocs-material
    - mkdocs build
    - mkdir .public
    - cp -r site/* .public
    - ls -la .public  # 列出 .public 目錄的內容
    - mv .public public
  artifacts:
    paths:
      - public

pages:
  stage: pages
  script:
    - echo "Using public directory for pages"
    - ls -la public  # 列出 public 目錄的內容
  dependencies:
    - deploy_job
  artifacts:
    paths:
      - public
  only:
    - main